feat: 회원기술정보 생성(#8)
Rubminds/rubminds-backend pull request #13
Opened 2021-11-25 15:14 UTC by jiyeon-agnes-lee

#8 

- User
- UserService
- UserController
- UserSkill

보시고 피드백 부탁드립니다!

2021-11-26 06:08 UTC, donup3 requested changes

2021-11-26 06:08 UTC, donup088 commented on src/main/java/com/rubminds/api/skill/web/SkillController.java
> +    }
다른 api들과 마찬가지로 dto 를 return 하도록 하는 것이 좋아보입니다

2021-11-26 06:08 UTC, donup088 commented on src/main/java/com/rubminds/api/user/service/UserService.java
>      }
signup 메서드에 skill을 넘기지 않고 
userskill을 create 매서드로 만들고 만든 userskill을 signup 으로 넘겨주고 값을 넣어주면 어떨까요?

2021-11-27 14:40 UTC, jiyeon-agnes-lee commented
#8 

코드 수정후 다시 PR 올립니다!

2021-11-28 00:26 UTC, donup3 approved these changes

2021-11-28 00:26 UTC, donup088 commented on src/main/java/com/rubminds/api/user/dto/AuthRequest.java
>  }
회원가입할때 기술을 여러개 받을 수 있으니 List<Long> 으로 하면 될 것 같아요

2021-11-28 00:26 UTC, merged