Feature/3
Rubminds/rubminds-backend pull request #14
Opened 2021-11-25 19:28 UTC by kikiplus1

restdocs 작성을 위한 test/postcontrollertest에서 response 값이 계속 null이라고 에러가 뜹니다.. 
대체 어딜 고쳐야 할지.. 코드 한번 봐주시면 감사하겠습니다 ㅠㅠ 
#3

2021-11-26 06:09 UTC, donup3 requested changes

2021-11-26 06:09 UTC, donup3 commented on src/test/java/com/rubminds/api/user/web/PostControllerTest.java
> +        );
mvc.perform(put("/api/post/{postId}",1L)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request))
                .characterEncoding("UTF-8")
pathvariable 설정을 해주셔야해요 그리고 restdoc에 pathvarivable도 문서화를 해주셔야합니다

2021-11-26 06:09 UTC, donup3 commented on src/test/java/com/rubminds/api/user/web/PostControllerTest.java
> +
update api 맞는 postservice.update를 해줘야합니다

2021-12-01 15:24 UTC, kikiplus1 commented on src/test/java/com/rubminds/api/user/web/PostControllerTest.java
> +        );
수정완료하였습니다!

2021-12-01 15:25 UTC, kikiplus1 commented on src/test/java/com/rubminds/api/user/web/PostControllerTest.java
> +
> 
수정완료하였습니다!

>

2021-12-02 03:05 UTC, donup3 approved these changes

2021-12-02 03:05 UTC, merged