Feature/15 게시물스킬 저장/삭제
Rubminds/rubminds-backend pull request #16
Opened 2021-11-25 21:28 UTC by kikiplus1

#15

2021-12-01 16:04 UTC, kikiplus1 commented
@donup3 
이거 저장을 post저장할때 함께 하게 할지(양방향 웬만하면 안하는게 좋다하셔서 일단 이렇게 해봤습니다!)
지금 단건으로 하나하나 저장하게 해놓았는데(아에 프론트에서 하나 선택할때마다 하나씩 저장되는 형식을 생각함.)
List로 받는걸로 다시 해야할지
보고 피드백 부탁드립니다! ㅠㅠ

2021-12-02 03:09 UTC, donup3 commented
게시물작성할 때 사용자가 입력하는 스킬과 DB에 저장되어 있는 스킬을 따로 받아야 하기 때문에 이 두가지를 따로 리스트로 받아야 할 것 같아요 :)

2021-12-02 03:13 UTC, donup3 requested changes

2021-12-02 03:13 UTC, donup3 commented on src/main/java/com/rubminds/api/skill/dto/PostSkillRequest.java
>  }
자바에서 변수명은 _ 사용이 아니라 skillId 이렇게 camel case로 작성하시는 것이 좋습니다

2021-12-02 03:13 UTC, donup3 commented on src/main/java/com/rubminds/api/post/web/PostController.java
> +
메서드의 시작은 소문자로 하는 것이 좋을 것 같아요

2021-12-02 03:13 UTC, donup3 commented on src/main/java/com/rubminds/api/skill/web/PostSkillControllor.java
> +}
게시물 스킬 api는 게시물  api 안에서 한번에 처리하고 따로 api를 안만드는 것이 좋아보여요

2021-12-04 20:49 UTC, kikiplus1 commented
#24 로 이동

2021-12-04 20:49 UTC, closed without merging