feat : postskill 읽고,쓰기,삭제,보기 post와 연동(#24)
Rubminds/rubminds-backend pull request #27
Opened 2021-12-05 14:16 UTC by kikiplus1

#24

2021-12-05 14:33 UTC, donup3 requested changes

2021-12-05 14:33 UTC, donup3 commented on src/main/java/com/rubminds/api/post/service/PostService.java
>      }
@Transactional 이 중복되어있는 부분이 있는 것 같아요 조회와 데이터 변하는 부분을 나눠서 @Transactional을 다르게 붙이는게 좋아보여요

2021-12-05 14:33 UTC, donup3 commented on src/main/java/com/rubminds/api/skill/domain/PostSkill.java
> +    @Id
테이블이름을 post_skill로 하는건 어떨까요?

2021-12-05 15:12 UTC, kikiplus1 commented on src/main/java/com/rubminds/api/post/service/PostService.java
>      }
@donup3 수정 완료하였습니다!

2021-12-05 15:49 UTC, kikiplus1 commented on src/main/java/com/rubminds/api/skill/domain/PostSkill.java
> +    @Id
@donup3 수정 완료하였습니다!

2021-12-06 02:45 UTC, donup3 commented on src/main/java/com/rubminds/api/post/service/PostService.java
> +        return PostResponse.Info.build(post,post.getWriter(),skills);
post 와 post.getWriter()를 나눠서 넘겨주는 이유가 있을까요?? response class에서 post만 받고 안에서 writer 사용해도 될 것 같아요

2021-12-06 02:47 UTC, donup3 requested changes

2021-12-06 02:47 UTC, donup3 commented on src/main/java/com/rubminds/api/post/service/PostService.java
>      }
@Transactional 을 class 전체에 사용하도록 되어 있어서 수정이 필요해보입니다~

2021-12-06 15:08 UTC, kikiplus1 commented on src/main/java/com/rubminds/api/post/service/PostService.java
> +        return PostResponse.Info.build(post,post.getWriter(),skills);
@donup3  수정하였습니다!

2021-12-06 15:09 UTC, kikiplus1 commented on src/main/java/com/rubminds/api/post/service/PostService.java
>      }
@donup3 @transactional(readonly=true)로 수정하였는데 맞을까요?

2021-12-07 01:34 UTC, donup3 approved these changes

2021-12-07 01:34 UTC, merged