feat : CostomSkill POST와 연동해 CRUD완료 (#28)
Rubminds/rubminds-backend pull request #29
Opened 2021-12-08 15:17 UTC by kikiplus1

@donup3 
costomskill완료하였습니다!(#28)
(계속해서 issu번호를 commit할때 메세지에 넣는걸 까먹네요 ㅠㅠ 나중에야알았습니다 죄송합니다)ㅠㅠ

restdocs를 생성하기위한
postcontrollerTest.java에 맨 마지막 post_detail (포스트 디테일 가져오기) 부분에서
계속해서 

Cannot document response fields as the response body is empty
org.springframework.restdocs.snippet.SnippetException: Cannot document response fields as the response body is empty
org.springframework.restdocs.mockmvc.RestDocumentationResultHandler.handle(RestDocumentationResultHandler.java:52)
org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)

이런식으로 에러가 납니다 ㅠㅠ 이response 필드는 전부 채운것 같은데 대체 뭐가 문제인지 잘 모르겠습니다 ㅠ
array부분을 빼도 문제고 안빼도 같은 에러가 발생합니다!

혹시몰라서 get해올때의 response값 첨부합니다.
{
  "id": 5,
  "writer": "테스터1",
  "title": "123",
  "content": "수정완료",
  "headcount": 1,
  "kinds": "PROJECT",
  "meeting": "BOTH",
  "postsStatus": "GATHERING",
  "region": "서울",
  "postSkills": [
    {
      "postSkillId": 19,
      "name": "TypeScript"
    },
    {
      "postSkillId": 20,
      "name": "JavaScript"
    }
  ],
  "costomSkills": [
    {
      "costomSkillId": 11,
      "name": "firebase"
    },
    {
      "costomSkillId": 12,
      "name": "mysql"
    }
  ]
}

2021-12-09 02:41 UTC, donup3 requested changes

2021-12-09 02:41 UTC, donup3 commented on src/test/java/com/rubminds/api/user/web/PostControllerTest.java
> +    }
mocking한 서비스 객체에서 매서드 실행할때 얻어오는 값을 given으로 값을 스터빙 해줘야합니다:)

2021-12-09 13:58 UTC, kikiplus1 commented on src/test/java/com/rubminds/api/user/web/PostControllerTest.java
> +    }
> mocking한 서비스 객체에서 매서드 실행할때 얻어오는 값을 given으로 값을 스터빙 해줘야합니다:)
@donup3 
수정완료하였습니다!

2021-12-10 01:31 UTC, donup3 approved these changes

2021-12-10 01:31 UTC, merged