[backend] 프로필이미지 CRUD
Rubminds/rubminds-backend pull request #31
Opened 2021-12-10 14:56 UTC by jiyeon-agnes-lee

#22 

S3와 연결해서 프로필 이미지 CRUD 생성 후 UserAPI도 함께 수정했습니다.

2021-12-11 11:18 UTC, donup3 requested changes

2021-12-11 11:18 UTC, donup3 commented on src/main/java/com/rubminds/api/file/exception/FileExtensionException.java
> +}
String.format을 쓰신 이유가 있을까요?

2021-12-11 11:18 UTC, donup3 commented on src/main/java/com/rubminds/api/file/dto/FileRequest.java
> +}
FIleRequest라는 클래스 이름보단 FIleDto나 다르게 공통적으로 쓰일 수 있는 이름이 좋아보여요

2021-12-11 11:18 UTC, donup3 commented on src/main/resources/application.yml
> +    publicUrl: https://rubminds.s3.ap-northeast-2.amazonaws.com
보안상 gitignore 처리하고 다른 파일로 관리하는 것이 좋습니다

2021-12-11 11:18 UTC, donup3 commented on src/main/java/com/rubminds/api/user/web/UserController.java
>      }
MultipartHttpServletRequest 를 쓰지않고 기존의 request data에 mutipartfile을 쓰시면 될 것 같아요

2021-12-11 11:18 UTC, donup3 commented on src/main/java/com/rubminds/api/user/service/UserService.java
>      }
코드중복도 있어보이고 하나의 서비스 메서드에 null체크가 너무 많아보여요 다른 메서드로 옮길 수 있을 것 같습니다

2021-12-11 11:18 UTC, donup3 commented on src/main/java/com/rubminds/api/user/service/UserService.java
> +    }
MultipartHttpServletRequest  말고 request dto를 사용하셔서 하드코딩은 피하는것이 좋아보이네요

2021-12-11 11:18 UTC, donup3 commented on src/main/java/com/rubminds/api/user/dto/AuthRequest.java
> +        private String isAvatarChanged;
skillId를 list 에서 String으로 바꾼이유가 있으실까요?

2021-12-11 11:18 UTC, donup3 commented on src/main/java/com/rubminds/api/user/service/UserService.java
> +    public AuthRequest.Update insertUpdate(MultipartHttpServletRequest multipartHttpServletRequest){
service layer는 다른 service layer를 의존하지 않는 것이 좋지 않을까요??

2021-12-16 17:24 UTC, jiyeon-agnes-lee commented
#22 
Comment 참고하여 수정하였습니다!

2021-12-16 17:31 UTC, jiyeon-agnes-lee commented
#22 
Comment 참고하여 수정하였습니다!

2021-12-17 00:18 UTC, donup3 approved these changes

2021-12-17 00:19 UTC, merged