feature : team_user 생성,삭제,상태변경 및 post,team과의 연동(#34)
Rubminds/rubminds-backend pull request #35
Opened 2021-12-12 15:30 UTC by kikiplus1

<post>
- 게시글 creat시에 팀 자동생성 -> 팀장을 team_user에 같이 저장하게끔 변경
- 게시글 delete시에 해당 게시글의 팀원, 팀장 같이 삭제하게끔 변경

<team>
- team 조회 시 팀원들도 같이 조회하게끔 변경

<team_user>
- team user : user추가, user삭제, user의 finish 상태변경 기능 추가

말씀하신대로 필요한 인자값만 보낼 수 있도록 dto최대한 작성해 봤는데 이부분은 나중에
모각코 할때 프론트와 상의 하고 재수정 해보겠습니다!

restdocs는 comment 받고 PR후 따로 issue 파서 작성하도록 하겠습니다!

@donup3

2021-12-13 01:06 UTC, donup3 requested changes

2021-12-13 01:06 UTC, donup3 commented on src/main/java/com/rubminds/api/team/domain/TeamUser.java
> +    }
grade 사용이유가 팀장인것을 확인하려고 하는 목적이면 team 테이블에 admin이 있기때문에 필요없을 것 같아요

2021-12-13 01:06 UTC, donup3 commented on src/main/java/com/rubminds/api/team/web/TeamUserController.java
> +
saveTeamUse가 팀원을 초대하는 목적이라면 request에 들어있는 id들은 pathvarible을 사용하는 것이 좋아보입니다!

2021-12-13 14:42 UTC, kikiplus1 commented on src/main/java/com/rubminds/api/team/domain/TeamUser.java
> +    }
@donup3 
수정하였습니다!

2021-12-13 14:42 UTC, kikiplus1 commented on src/main/java/com/rubminds/api/team/web/TeamUserController.java
> +
@donup3 
수정하였습니다!

2021-12-14 00:50 UTC, donup3 approved these changes

2021-12-14 05:47 UTC, merged