[backend] 회원가입 생성
Rubminds/rubminds-backend pull request #4
Opened 2021-11-18 08:37 UTC by jiyeon-agnes-lee

#2

2021-11-18 10:27 UTC, donup3 requested changes

2021-11-18 10:27 UTC, donup3 commented on src/main/java/com/rubminds/api/user/domain/User.java
> +    }
회원가입이라서 create나 signup 으로하는게 어떨까요?? 개인 정보 수정할 때 update 메서드가 또 필요해보여요! 그리고 소셜로그인 부분에서 success handler 부분 보시면 signupCheck는 이미 true로 값이 설정되어 있을 거에요 따로 업데이트 안시켜줘도 됩니다

2021-11-18 10:27 UTC, donup3 commented on src/main/java/com/rubminds/api/user/exception/DuplicateNicknameException.java
> +}
IllegalStateException 으로 하는 것보다 이미 있는 InvalidValue 사용하는 건 어떨까요?

2021-11-18 10:27 UTC, donup3 commented on src/main/java/com/rubminds/api/user/service/UserService.java
> +    @Transactional
@Transactional 이 중복되었어요~

2021-11-18 10:27 UTC, donup3 commented on src/main/java/com/rubminds/api/user/web/UserController.java
> +    }
HttpServletResponse  는 필요없어보여요:)

2021-11-18 12:07 UTC, jiyeon-agnes-lee commented
코드 업데이트 후 다시 PR하겠습니다 !

2021-11-18 12:10 UTC, jiyeon-agnes-lee commented
#2
코드 수정 후 다시 업로드 하였습니다.
1.  메서드 명 변경 (update -> signup)
2. signupCheck 삭제
3. InvalidValueException으로의 변경
4. @Transactional 중복 제거
5. 불필요한 코드 제거(HttpServletResponse)

2021-11-19 03:04 UTC, donup3 approved these changes

2021-11-19 03:04 UTC, merged