[backend] 팀원평가 기능 구현
Rubminds/rubminds-backend pull request #49
Opened 2021-12-22 11:53 UTC by jiyeon-agnes-lee

#44 
팀원 평가, 팀원 목록 생성하여 PR올립니다!

2021-12-22 12:49 UTC, donup3 requested changes

2021-12-22 12:49 UTC, donup3 commented on src/main/java/com/rubminds/api/team/Service/TeamUserService.java
> +    }
복잡한 로직이 너무 알아보기 힘들어보입니다. 로직을 분리하시거나  더 간단히 하시면 좋을 것 같아요 아래로직도 모두 간단히 할 수 있을 것 같아요

2021-12-22 13:32 UTC, jiyeon-agnes-lee commented on src/main/java/com/rubminds/api/team/Service/TeamUserService.java
> +    }
네 좀 더 간단히 작성해보겠습니다!

2021-12-23 17:24 UTC, jiyeon-agnes-lee commented
#44 
코멘트 참고하여 로직을 수정해보았습니다. 확인 부탁드려요:)

2021-12-24 10:03 UTC, donup3 requested changes

2021-12-24 10:03 UTC, donup3 commented on src/main/java/com/rubminds/api/team/web/TeamUserController.java
pathvariable을 거의 사용하지 않고 id 값들을 requestparam으로 사용하시는 이유가 있으신가요??

2021-12-24 10:03 UTC, donup3 commented on src/main/java/com/rubminds/api/team/Service/TeamUserService.java
>  }
service의 복잡한 로직들을 private 매서드를 사용하여 분리할 수도 있지만 private 메서드가 너무 많아지는 것 같아서 도메인 layer로 옮길 수도 있습니다

2021-12-24 14:15 UTC, jiyeon-agnes-lee commented on src/main/java/com/rubminds/api/team/web/TeamUserController.java
팀 유저 부분에서는 유저 추가 부분에서는 두 가지의 아이디 값을 받으니 객체 형식으로 받아야겠다고 생각했고, 팀 유저 리스트는 리스트 출력의 방식을 전체출력과, 페이지형식출력 중 고민하다가 페이지로 변경될 지 모른다고 생각해 Param으로 작성하였습니다! 이에 대해서는 좀 더 공부해보도록 하겠습니다. 우선 다른 코드들과 통일하여 pathvariable형식으로 수정하도록 하겠습니다!!

2021-12-24 14:15 UTC, jiyeon-agnes-lee commented on src/main/java/com/rubminds/api/team/Service/TeamUserService.java
>  }
네! 다시 수정해보도록 하겠습니다!!

2021-12-26 14:55 UTC, jiyeon-agnes-lee commented
다시 한 번 수정하여 코드를 정리해보았습니다 ! 확인부탁드려요

2021-12-28 01:30 UTC, donup3 approved these changes

2021-12-28 01:30 UTC, merged