[backend] 회원정보 조회
Rubminds/rubminds-backend pull request #6
Opened 2021-11-18 10:24 UTC by jiyeon-agnes-lee

#5

2021-11-18 10:35 UTC, donup3 requested changes

2021-11-18 10:35 UTC, donup3 commented on src/main/java/com/rubminds/api/user/web/UserController.java
> +    }
어느 곳에 쓰이는 api 일까요???

2021-11-18 10:35 UTC, donup3 commented on src/main/java/com/rubminds/api/user/web/UserController.java
> +    }
HttpServletResponse 빼셔도 됩니다~

2021-11-18 10:35 UTC, donup3 commented on src/main/java/com/rubminds/api/user/service/UserService.java
> +    }
@CurrentUser 는  controller layer에서 사용해서 로그인한 유저를 가져오는거에요 getUser해서 service layer로 넘기고 service에서는 로그인한 User 객체를 사용하시면 됩니다

2021-11-18 10:40 UTC, jiyeon-agnes-lee commented on src/main/java/com/rubminds/api/user/web/UserController.java
> +    }
자기 자신 회원 정보가 아닌 타인 회원정보 조회로 생각해서 만들었어요! 원하는 회원의 정보를 가져오는 api입니다.

2021-11-18 12:16 UTC, jiyeon-agnes-lee commented
코드 수정 후 다시 PR하겠습니다 !

2021-11-18 12:18 UTC, jiyeon-agnes-lee commented
#5 
코드 수정완료하였습니다.
1. 불필요한 코드 제거
2.  layer 구분하도록 코드 수정

2021-11-19 03:10 UTC, donup3 approved these changes

2021-11-19 03:27 UTC, merged